# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: self-hosted-windows

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: Use .net SDK
  inputs:
    packageType: sdk
    version: 6.0.413

- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: build
    projects: $(solution)
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Run integration tests
  inputs:
    command: test
    projects: '**/Tests.Integration/*.csproj'
    publishTestResults: true
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Run unit tests
  inputs:
    command: test
    projects: '**/*/Tests.csproj'
    publishTestResults: true
    configuration: $(buildConfiguration)